# the workflow name
name: Run on pull-request and push

# WHEN this will run
on:
  pull_request:
    branches: [horse]
  push:
    branches: [cat]
# on: [ push, pull_request ]

# Obj of jobs
jobs:
  # job name, must me kebab cased && val is an object
  run-checkout-on-ull-pr:  
    # run on the "learning" environment
    environment: logless-learning
    # type of vm to run on
    runs-on: ubuntu-latest
    # arr of objs, representing steps
    steps:
      - name: List Files Before action
        run: |
          pwd
          ls -a
      - name: checkout action
        uses: actions/checkout@v1
      - name: List repo docs after checkout action
        run: |
          echo "PWD HERE: ->"
          pwd
          echo "LS -A HERE: ->"
          ls -a
