# the workflow name
name: Run with env vars
# on: push
on:
  pull_request:
    branches: [horse]
  push:
    branches: [cat]
# pass env vars as obj
env:
  # keys here are available in ALL JOBS below
  WF_ENV: Available to all jobs

jobs:
  log-env:
    # keys here are ONLY available in THIS job
    env:
      LOG_ENV_VAR: only available in log-env step
    runs-on: ubuntu-latest
    steps:
      - name: Log Env Vars
        env: 
          STEP_VAR: only available in Log Env Vars step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "LOG_ENV_VAR: ${LOG_ENV_VAR}"
          echo "STEP_VAR: ${STEP_VAR}"
      - name: second step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "LOG_ENV_VAR: ${LOG_ENV_VAR}"
          echo "STEP_VAR: ${STEP_VAR}"
  log-default-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Logging Default Env 
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "WF_ENV: ${WF_ENV}"
          echo "LOG_ENV_VAR: ${LOG_ENV_VAR}"
          echo "STEP_VAR: ${STEP_VAR}"
