# the workflow name
name: Run with env vars
on: push
# pass env vars as obj
env:
  # keys here are available in ALL JOBS below
  WF_ENV: Available to all jobs

jobs:
  log-env:
    # keys here are ONLY available in THIS job
    env:
      LOG_ENV_VAR: only available in log-env step
    runs-on: ubuntu-latest
    steps:
      - name: Log Env Vars
        env: 
          STEP_VAR: only available in Log Env Vars step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "LOG_ENV_VAR: ${LOG_ENV_VAR}"
          echo "STEP_VAR: ${STEP_VAR}"
      - name: second step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "LOG_ENV_VAR: ${LOG_ENV_VAR}"
          echo "STEP_VAR: ${STEP_VAR}"