name: Create Rando TxtFile

on: [ push ]

jobs:
  on_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
      contents: write
    steps:
      - name: push rando file
        run: |
          pwd
          ls -a
          echo "git init:"
          git init
          echo "git remote add origin:"
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          echo "set git config:"
          git config --global user.email "test-email-from-workflow@asdf.com"
          git config --global user.name "workflow-bot"
          echo "checkout master:"
          git checkout master
          echo "set branch to master:"
          git branch --set-upstream-to=origin/master
          echo "git pull:"
          git pull
          echo "ls -a:"
          ls -a
          echo $RANDOM >> randoNumber.txt
          echo "should show randoNumber.txt:"
          la -a
          echo "git add, commit and push:"
          git add -a
          git commit -m 'message from workflow'
          git push
