name: Create Rando TxtFile

on: [ push ]

jobs:
  on_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
      - name: push rando file
        run: |
          echo "pwd:"
          pwd
          echo "ls -a:"
          ls -a
          echo "git init:"
          git init
          echo "git remote add origin:"
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          echo "set git config"
          git config --global user.email "test-email-from-workflow@asdf.com"
          git config --global user.name "workflow-bot"
          echo "checkout main"
          git checkout main
          echo "set branch to main"
          git branch --set-upstream-to=origin/main
          echo "git pull"
          git pull
          echo "ls -a:"
          ls -a
          echo $RANDOM >> randoNumber.txt
          echo "should show randoNumber.txt"
          la -a
          echo "git add, commit and push:"
          git add -a
          git commit -m 'message from workflow'
          git push
