name: Create Rando TxtFile

on: [ push ]

jobs:
  on_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
      contents: write
    steps:
      - name: push rando file
        run: |
          pwd
          ls -a
          echo "ECHO: git init"
          git init
          echo "ECHO: git remote add origin"
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          echo "ECHO: set git config"
          git config --global init.defaultBranch main
          git config --global user.email "ericjlaursen@gmail.com"
          git config --global user.name "Jake"
          echo "ECHO: --LOGGING GIT CONFI"
          git config --list
          git fetch
          echo "ECHO: checkout main"
          git checkout main
          echo "ECHO: set branch to main"
          git branch --set-upstream-to=origin/main
          echo "ECHO: git pull"
          git pull
          echo "ECHO: ls -a"
          ls -a
          echo $RANDOM >> randoNumber.txt
          echo "ECHO: should show randoNumber.txt"
          ls -a
          echo "ECHO: git add, commit and push"
          git add .
          git commit -m 'message from workflow'
          git push
