name: Print Function Deets
# on: push
on:
  pull_request:
    branches: [horse]
  push:
    branches: [cat]
jobs:
  show-text:
    runs-on: ubuntu-latest
    steps:
      - name: print a bunch of stuff
        run: |
         echo ${{contains('hello', 'll')}}
         echo ${{startsWith('hello', 'he')}}
         echo ${{endsWith('hello', 'lo')}}
         echo ${{format('Hello {0} {1} {2}', 'World', '!', '!')}}