name: Use-Node-Version
on: push
jobs:
  node-version-setup:
    runs-on: ubuntu-latest
    steps:
      # log the current version of node
      - name: Log Node Version
        run: node --version
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Log Node Version AFTER action
        run: node --version
      